chore: move FFMPEG custom build to overlay

diff --git a/overlay/ports/ffmpeg/build.sh.in b/overlay/ports/ffmpeg/build.sh.in
--- a/overlay/ports/ffmpeg/build.sh.in
+++ b/overlay/ports/ffmpeg/build.sh.in
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-set -e
+set -ex
 
 move_binary() {
     SOURCE=$1
@@ -99,6 +99,26 @@ build_ffmpeg() {
     echo "=== CONFIGURING ==="
 
     sh "$PATH_TO_SRC_DIR/configure" "--prefix=$PATH_TO_PACKAGE_DIR" @CONFIGURE_OPTIONS@ --arch=${BUILD_ARCH} ${!OPTION_VARIABLE} $@
+
+    if [ "@FEDORA_FFMPEG_FREE_SAFE@" = "ON" ]
+    then
+        # Paranoia check - https://src.fedoraproject.org/rpms/ffmpeg/blob/f41/f/ffmpeg.spec#_726	
+        # DECODER	
+        for i in H264 HEVC HEVC_RKMPP VC1 VVC; do	
+            grep -q "#define CONFIG_${i}_DECODER 0" "$PATH_TO_BUILD_DIR/config_components.h" || (>&2 echo "ABORT! Didn't find ${i}_DECODER" && exit 1)
+        done 
+            
+        # ENCODER	
+        for i in LIBX264 LIBX264RGB LIBX265; do	
+            grep -q "#define CONFIG_${i}_ENCODER 0" "$PATH_TO_BUILD_DIR/config_components.h" || (>&2 echo "ABORT! Didn't find ${i}_ENCODER" && exit 1)
+        done
+            
+        for i in H264 HEVC; do	
+            for j in MF VIDEOTOOLBOX; do	
+                grep -q "#define CONFIG_${i}_${j}_ENCODER 0" "$PATH_TO_BUILD_DIR/config_components.h" || (>&2 echo "ABORT! Didn't find ${i}_${j}_ENCODER" && exit 1)
+            done
+        done
+    fi
 
     echo "=== BUILDING ==="
 
